
sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

services:
  - mysql

php:
  #  - 5.6
  - 7.0
#  - 7.1
#  - 7.2

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test
#  - WP_PROJECT_TYPE=plugin WP_VERSION=5.0.4 WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

#matrix:
#  allow_failures:
#    - php: nightly

before_script:
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION
  - composer install

script:
  #  - wget https://phar.phpunit.de/phpunit-nightly.phar
  #  - php phpunit-nightly.phar
  #  - phpunit
  - vendor/bin/phpunit
  - cd wp-tests/spec && bundle exec rspec test.rb