name: Deploy to WordPress.org
on:
  push:
    tags-ignore:
      - "*.dev"
      - "*.dev.*"
      - "*.beta"
      - "*.beta.*"
      - "*.alpha"
      - "*.alpha.*"
      - "*.rc.*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Subversion
        run: sudo apt-get install subversion
      - name: WordPress Plugin Deploy
        with:
          generate-zip: true
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: groundhogg
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
